language: node_js
node_js:
  - "iojs"
  - "7"

language: rust
script:
  - cargo build --verbose --all
  - cargo build --target=wasm32-unknown-unknown --verbose --all
cache: cargo

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true