[package]
name = "ln-rust-research"
version = "0.1.0"
authors = ["Ilya Druzhinin <ilya.druzh@gmail.com>"]

[dependencies]
bitcoin = "0.13.2"
bitcoin-rpc-json = "0.1.0"
bitcoin-bech32 = "0.8.0"
serde="1.0.70"
tokio = "0.1"
lnd-rust = "0.1"
grpc = "0.5.0"